name: github pages

on:
  schedule:
    - cron: '0 0 * * *' # Auto-trigger workflow everyday at 00:00
  push:
    branches: [master]
  pull_request:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Doxygen-1.9.3
        run: |
          echo "Install wget"
          sudo apt install wget
          echo "Fetching binary distribution"
          wget https://www.doxygen.nl/files/doxygen-1.9.3.linux.bin.tar.gz
          echo "Extract files from tar file"
          tar -xvf doxygen-1.9.3.linux.bin.tar.gz

      - name: Install Jinja2
        run: pip install -U jinja2

      - name: Install Sphinx
        run: |
          pip install sphinx
          pip install pydata_sphinx_theme

      - name: Install Breathe
        run: pip install breathe

      - name: Doxygen Action
        run: |
          echo "Preparing files for documentation"
          make docs
          mv doxygen-1.9.3/bin/doxygen .
          echo "Generating XML output"
          ./doxygen
          sudo mv docs/xml concord-docs/docs

      - name: Breathe Action
        run: make -C concord-docs/docs html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./concord-docs/docs/build/html
